// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'animals_model.freezed.dart';
// optional: Since our AnimalsModel class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'animals_model.g.dart';

@freezed
class AnimalsModel with _$AnimalsModel {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory AnimalsModel({
    required String name,
    required String latinName,
    required String animalType,
    required String activeTime,
    required String lengthMin,
    required String lengthMax,
    required String weightMin,
    required String weightMax,
    required String lifespan,
    required String habitat,
    required String diet,
    required String geoRange,
    required String imageLink,
    required int id,
  }) = _AnimalsModel;

  factory AnimalsModel.fromJson(Map<String, Object?> json) =>
      _$AnimalsModelFromJson(json);
}
// class AnimalsModel {
//   late final String name;
//   late final String latinName;
//   late final String animalType;
//   late final String activeTime;
//   late final String lengthMin;
//   late final String lengthMax;
//   late final String weightMin;
//   late final String weightMax;
//   late final String lifespan;
//   late final String habitat;
//   late final String diet;
//   late final String geoRange;
//   late final String imageLink;
//   late final int id;

//   AnimalsModel({
//     required this.name,
//     required this.latinName,
//     required this.animalType,
//     required this.activeTime,
//     required this.lengthMin,
//     required this.lengthMax,
//     required this.weightMin,
//     required this.weightMax,
//     required this.lifespan,
//     required this.habitat,
//     required this.diet,
//     required this.geoRange,
//     required this.imageLink,
//     required this.id,
//   });

//   AnimalsModel.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     latinName = json['latin_name'];
//     animalType = json['animal_type'];
//     activeTime = json['active_time'];
//     lengthMin = json['length_min'];
//     lengthMax = json['length_max'];
//     weightMin = json['weight_min'];
//     weightMax = json['weight_max'];
//     lifespan = json['lifespan'];
//     habitat = json['habitat'];
//     diet = json['diet'];
//     geoRange = json['geo_range'];
//     imageLink = json['image_link'];
//     id = json['id'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['name'] = this.name;
//     data['latin_name'] = this.latinName;
//     data['animal_type'] = this.animalType;
//     data['active_time'] = this.activeTime;
//     data['length_min'] = this.lengthMin;
//     data['length_max'] = this.lengthMax;
//     data['weight_min'] = this.weightMin;
//     data['weight_max'] = this.weightMax;
//     data['lifespan'] = this.lifespan;
//     data['habitat'] = this.habitat;
//     data['diet'] = this.diet;
//     data['geo_range'] = this.geoRange;
//     data['image_link'] = this.imageLink;
//     data['id'] = this.id;
//     return data;
//   }
// }
