// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jzdkZa2cLSSWt9MIFvXc-vUgIcC2sGs',
    appId: '1:432556866099:android:e2b495f2f7aa31eef00146',
    messagingSenderId: '432556866099',
    projectId: 'animals-26ff3',
    storageBucket: 'animals-26ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJwy1z6sqJGg42fu2AY6M6GR-zYGo0xI',
    appId: '1:432556866099:ios:362395b8ba79c3a6f00146',
    messagingSenderId: '432556866099',
    projectId: 'animals-26ff3',
    storageBucket: 'animals-26ff3.appspot.com',
    iosClientId: '432556866099-bb4jmej9dj2vdgeigckrpkvgtopktcs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.animals',
  );
}
